import {
  Navbar,
  Button,
  Container,
  Row,
  Col,
  Form,
  Card,
  ProgressBar,
} from 'react-bootstrap';
import Head from 'next/head';
import Link from 'next/link';
import styles from '../styles/Dashboard.module.css';
import React, { useRef, useState, useEffect } from 'react';
import { useAuth } from './contexts/AuthContext';
import firebase from 'firebase';
import { Animated } from 'react-animated-css';
import { collection, addDoc, setDoc, doc, query } from 'firebase/firestore';
import Avatar from '../public/favicon.ico';
import Image from 'next/image';
import Overview from '../components/Overview';

export default function Dashboard() {
  const [currentPage, setCurrentPage] = useState('Overview');

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Play:wght@400;700&family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap"
          rel="stylesheet"
        />
        <link
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
          crossOrigin="anonymous"
        />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.min.css"
        ></link>
        <script
          src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
          integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
          crossorigin="anonymous"
        />
      </Head>

      <Container fluid>
        <Row
          style={{
            height: '100vh',
          }}
        >
          <Col md={2} style={{ padding: '50px' }}>
            <Animated animationIn="fadeInLeft">
              <div style={{ textAlign: 'center' }}>
                <Link href="/">
                  <Navbar.Brand
                    style={{
                      fontWeight: 900,
                      fontSize: 40,
                      textAlign: 'center',
                      margin: '0',
                    }}
                  >
                    Pello.
                  </Navbar.Brand>
                </Link>
              </div>

              <div
                style={{
                  verticalAlign: 'middle',
                  textAlign: 'center',
                  marginTop: '150px',
                }}
              >
                <Image src={Avatar} height={100} width={100} />
                <h3 style={{ fontWeight: 'bold', marginTop: '25px' }}>
                  Rey Granda
                </h3>
                <p style={{ fontWeight: 900, color: '#BBBBBB' }}>
                  reygdev@gmail.com
                </p>
              </div>

              <div style={{ marginTop: '100px' }}>
                <li
                  style={{
                    listStyle: 'none',
                    marginBottom: '50px',
                    marginLeft: '30px',
                    fontWeight: 900,
                  }}
                >
                  {currentPage === 'Overview' && (
                    <Button
                      variant="dark"
                      style={{
                        padding: '10px 80px 10px 20px',
                        textAlign: 'left',
                      }}
                      onClick={() => {
                        setCurrentPage('Overview');
                      }}
                    >
                      Overview
                    </Button>
                  )}

                  {currentPage !== 'Overview' && (
                    <Button
                      variant="light"
                      style={{
                        padding: '10px 80px 10px 20px',
                        textAlign: 'left',
                      }}
                      onClick={() => {
                        setCurrentPage('Overview');
                      }}
                    >
                      Overview
                    </Button>
                  )}
                </li>

                <li
                  style={{
                    listStyle: 'none',
                    marginBottom: '50px',
                    marginLeft: '30px',
                    fontWeight: 900,
                  }}
                >
                  {currentPage === 'Tasks' && (
                    <Button
                      variant="dark"
                      style={{
                        padding: '10px 80px 10px 20px',
                        textAlign: 'left',
                      }}
                      onClick={() => {
                        setCurrentPage('Tasks');
                      }}
                    >
                      Tasks
                    </Button>
                  )}

                  {currentPage !== 'Tasks' && (
                    <Button
                      variant="light"
                      style={{
                        padding: '10px 80px 10px 20px',
                        textAlign: 'left',
                        fontWeight: 900,
                      }}
                      onClick={() => {
                        setCurrentPage('Tasks');
                      }}
                    >
                      Tasks
                    </Button>
                  )}
                </li>
                <li
                  style={{
                    listStyle: 'none',
                    marginBottom: '50px',
                    marginLeft: '30px',
                    fontWeight: 900,
                  }}
                >
                  {currentPage === 'Team Members' && (
                    <Button
                      variant="dark"
                      style={{
                        padding: '10px 80px 10px 20px',
                        textAlign: 'left',
                      }}
                      onClick={() => {
                        setCurrentPage('Team Members');
                      }}
                    >
                      Overview
                    </Button>
                  )}

                  {currentPage !== 'Team Members' && (
                    <Button
                      variant="light"
                      style={{
                        padding: '10px 80px 10px 20px',
                        textAlign: 'left',
                        fontWeight: 900,
                      }}
                      onClick={() => {
                        setCurrentPage('Team Members');
                      }}
                    >
                      Team Members
                    </Button>
                  )}
                </li>
              </div>
            </Animated>
          </Col>
          <Col style={{ padding: '50px' }} md={10}>
            {currentPage === 'Overview' && <Overview />}
          </Col>
        </Row>
      </Container>
    </div>
  );
}
